### PR TITLE
Update only on non metered Internet and with the database unlocked

### PR DESCRIPTION
**Pull request by es20490446e**
@cmuench

https://github.com/es20490446e/pacman-auto-update

### CODE REVIEW

**Comment by cmuench** [comment]
@es20490446e thanks for the PR.
I have some questions.
Why did you remove the readme file?
Why did you move the license file into a sub directory info. Github is not recognize the file anymore.

**Comment by es20490446e** [comment]
I removed the readme file because it said nothing useful for 95% of users.

I moved the license under info because I considered that having it more organized was of greater use than having the license stated in the front page.

More generally:
https://signalvnoise.com/archives2/it_just_doesnt_matter.php

Everything should be taken as a suggestion.

**Comment by es20490446e** [comment]
It was possible to put the package files inside a "package" folder because, when building the package, the sources are cloned again inside the folder.

This is so the PKGBUILD also works outside the git repository. I have tested that everything works.

**Comment by cmuench** [comment]
@es20490446e The README file is for github. That should stay at the same position. Same is for the LICENSE which is automatocally detected by Github at this location.
If I publish a new package update the file PKGBUILD file has to be in the root of the repository. So this change IMHO breaks the automatic update process on AUR side.

**Comment by es20490446e** [comment]
It's at the root. The PKGBUILD fetches the sources inside the "package" folder.

**Comment by cmuench** [comment]
Yes, it maybe work if you manually create the package and do a "cd package" before.
What I mean is that the AUR build procewss looks for the PKGBUILD in the root of the repository.

**Comment by es20490446e** [comment]
Having a look at the AUR package, I see you misunderstood how it works 😯

On the AUR you place only the PKGBUILD and the ".install" file, at the root.

On GitHub you place any other file, anywhere you want.

Then on the AUR you tell the PKGBUILD that those other files are on GitHub by putting in it:
url="https://github.com/cmuench/pacman-auto-update"
source=(git+${url})

The idea is that the AUR only holds the packaging instructions specific to Arch, where the software itself is placed elsewhere and can work on any Linux.

**Comment by cmuench** [comment]
Yes, I understand what you mean. In this case it's a tool dedicated to Arch Linux. That's why I decided to mirror the code to Github 1:1.

**Comment by es20490446e** [comment]
The AUR should not hold the actual program, that's not the purpose of the AUR.

It shall only hold packaging code.

**Comment by es20490446e** [comment]
More broadly code duplication is considered a programming anti-pattern, as now you have to maintain the code in two places where only one is actually needed.

https://4.bp.blogspot.com/-4LgVTEh3A7U/VWTQpe4TLVI/AAAAAAAAMHk/MqkD3VwTzGc/s1600/dontrepeatyourself1.jpg

https://image.slidesharecdn.com/atrainingon3msinleanmanagement-151218043406/95/a-training-on-3-ms-in-lean-management-14-638.jpg?cb=1450413393

https://stackoverflow.com/questions/4226284/how-to-convince-a-colleague-that-code-duplication-is-bad

**Comment by cmuench** [comment]
@es20490446e Tried to build the package with your repo.
It's not building.

That's the output of makepkg

```
❯ makepkg
==> Erstelle Paket: pacman-auto-update 1602528360-1 (Sa 30 Jan 2021 10:15:59 CET)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> Aktualisiere das pacman-auto-update git Repo...
Fordere an von origin
==> Überprüfe source Dateien mit md5sums...
    pacman-auto-update ... Übersprungen
==> Entpacke Quellen...
  -> Erstelle Arbeitskopie des pacman-auto-update git Repos...
Zu neuem Branch 'makepkg' gewechselt
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Betrete fakeroot Umgebung...
==> Beginne package()...
cp: der Aufruf von stat für '/home/cmuench/.aur/pacman-auto-update-fork/package/src/pacman-auto-update/root/*' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
==> FEHLER: Ein Fehler geschah in package().
    Breche ab...
```

**Comment by es20490446e** [comment]
That's because "source" is your own repository, which isn't merged yet.

For testing, you can temporaly change "source" to:
https://github.com/es20490446e/pacman-auto-update

**Comment by cmuench** [comment]
@es20490446e ok. Got it.
I will try to include your change, but I will move the LICENSE and README back to the previous place.

**Comment by cmuench** [comment]
@es20490446e thanks for contributing.

**Comment by es20490446e** [comment]
You are welcome 👌😉

**Comment by cmuench** [comment]
@es20490446e I think at the end we can remove the package directory in this repo, right?

**Comment by es20490446e** [comment]
Yes, but those files should go to the AUR.

Except for one detail, the pkgver. I think that as it is know it won't be accepted on the AUR.

The PKGBUILD should rather be like [this](https://bin.privacytools.io/?03f38e1bc6ddbba3#HDKuAuQG6nhZMB6sihAdh4ikwRP6yEfREbXtj3CQERe9).

**Comment by cmuench** [comment]
@es20490446e It's already released as 1.1.0-1 in AUR

**Comment by es20490446e** [comment]
I think the PKGBUILD I'm providing is a little bit more correct. For example by generating the version programmatically versus manually, so mistakes are made imposible, or by providing networkmanager as dependency instead of the always present systemd. The changelog variable seems unused too.

Also I found that having the description in terms not of what the software is, but what it does, to be more meaningful:

- What it is: a systemd service triggered by a timer to run automatic pacman package updates.
- What it does: keeps official software packages automatically updated under non metered Internet.

**Comment by es20490446e** [comment]
Also having the versioning format as 1.1.0 could be useful if some other program could depend on this one, so you could know what kind of change the API had.

But it doesn't seem the case, so I guess an increasing integer is just simpler and easier to come with programatically.

**Comment by cmuench** [comment]
Version 1.1.0
What are you meaning? The "-1" at the end of "pkgrel" ?

**Comment by cmuench** [comment]
@es20490446e I think the dependency to networkmanager is not required. I run the package on a headless machine where no networkmanager package is installed and it works, well.

**Comment by es20490446e** [comment]
Currently you are using:
pkgver=1.1.0

The logic of having three numbers for describing the version is telling which kind of change the Application Programming Interface is getting:

- If the third number is changed, the change won't affect the API.
- If the second number is changed, the API is extended but nothing deprecated.
- If the first number is changed, the API has something deprecated.

But this program has no API because no other program is intended to call it, so what I'm saying is that it's just simpler to number it as:

pkgver=14

while increasing that number programatically with a pkgver() function.

Our new version of the program checks for metered wifi by using the command nmcli:
https://github.com/cmuench/pacman-auto-update/blob/49d0266385159384ae05f363e6dc3eedba1268a2/root/usr/lib/pacman-auto-update/pacman-auto-update#L5

Which is provided by networkmanager, as it can be checked with pacman:

> $ pacman --query --owns /bin/nmcli
> /usr/bin/nmcli is owned by networkmanager 1.28.1dev+7+g3f5df3cdc6-1

**Comment by cmuench** [comment]
@es20490446e The app uses semver. Thats's what you describe. Semver has always thee parts. So it's ok for me.
I did see that nmcli is part of network manager package. I changed the dependency. Hopefully it will not break my headless server.

**Comment by es20490446e** [comment]
What does it use for connecting to the Internet?

**Comment by cmuench** [comment]
systemd-networkd

**Comment by cmuench** [comment]
@es20490446e I am not sure if this change broken some systems.

**Comment by es20490446e** [comment]
Yes, combining systemd-networkd with networkmanager will create conflicts. I'm studying the case right now.

**Comment by es20490446e** [comment]
I say let's perform this checking only if network manager is installer, remove it as dependency, and investigate if there is a more comprehensive solution.

**Comment by es20490446e** [comment]
https://github.com/cmuench/pacman-auto-update/pull/6

**Pull request merged**
